vcs: git

prerequisites:
    - working-copy-check
    - display-last-changes
    - composer-json-check:
          composer: composer
    - composer-stability-check
    - command:
          cmd: composer outdated
    - command:
          cmd: git describe --abbrev=0 --tags

pre-release-actions:
    vcs-commit: ~

version-generator: semantic

version-persister: vcs-tag
